###
# Colors used:
# black -> colour0
# light purple 1 -> colour165
# light puple 2 -> colour135
# dark purple -> colour93
###

set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
set -g bell-action none
setw -g monitor-activity off

# clock mode
setw -g clock-mode-colour yellow

# copy mode
setw -g mode-style 'fg=#ffffff bg=#200c5a'

# panes
set -g pane-active-border-style 'fg=#5628e2'
set -g pane-border-style 'fg=#200c5a'

# statusbar
set -g status-position bottom
set -g status-justify left
set -g status-style 'bg=#5628e2'

set -g status-left ''
set -g status-left-length 10

set -g status-right-style 'fg=#ffffff bg=#5628e2'
set -g status-right 'day:%d %H:%M '
set -g status-right-length 50

setw -g window-status-current-style 'fg=white bg=#200c5a'
setw -g window-status-current-format ' #I #W #F '

# messages
set -g message-style 'fg=#ffffff bg=2140c6'
